export const EMAIL_LOGIN_SUCCESS = "EMAIL_LOGIN_SUCCESS";
export const EMAIL_LOGIN_FAIL = "EMAIL_LOGIN_FAIL";
export const LOG_OUT = "LOG_OUT";

export const CLEAR_DATA = "CLEAR_DATA";

export const GET_CARD_DETAILS = "GET_CARD_DETAILS";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const ADD_USER_INFORMATION = "ADD_USER_INFORMATION";
export const REMOVE_USER_INFORMATION = "REMOVE_USER_INFORMATION";

export const ADD_HISTORY = "ADD_HISTORY";
export const CLEAR_HISTORY = "CLEAR_HISTORY";

export const ADD_USER_LAT_LONG = "ADD_USER_LAT_LONG";
export const ADD_USER_ADDRESS = "ADD_USER_ADDRESS";
export const ADD_DEFAULT_LAT_LONG = "ADD_DEFAULT_LAT_LONG";
export const ADD_DEFAULT_ADDRESS = "ADD_DEFAULT_ADDRESS";

export const ADD_SUBSCRIPTION = "ADD_SUBSCRIPTION";
export const CLEAR_SUBSCRIPTION = "CLEAR_SUBSCRIPTION";
